app:
  name: ads
db:
  adapter: postgresql
  host: localhost
  user: postgres
  password: postgres
  url: <%= ENV['ADS_DATABASE_URL'] %>
pagination:
  page_size: 10
service:
  auth:
    url: http://localhost:3010/v1
  geocoder:
    url: http://localhost:3020/geocoder
rabbitmq:
  host: <%= ENV['RABBITMQ_HOST']%>
  user: <%= ENV['RABBITMQ_USER']%>
  password: <%= ENV['RABBITMQ_PASSWORD']%>
  consumer_pool: 10
logger:
  path: log/app.log
  level: info
